// PlayerGameEventEnum.ts
export enum NetworkEventEnum {
    PLAYER_JOINED = "PLAYER_JOINED",
    PLAYER_ACTION = "PLAYER_ACTION",
    PLAYER_LEFT = "PLAYER_LEFT",
    PLAYER_LOST_CONNECTION = "PLAYER_LOST_CONNECTION"
}