export enum GameEvent {
    PLAYER_ACTION = "PLAYER_ACTION",
    PLAYER_JOINED = "PLAYER_JOINED",
    PLAYER_LEFT = "PLAYER_LEFT",
    PLAYER_LOST_CONNECTION = "PLAYER_LOST_CONNECTION",
    GAME_END = "GAME_END",
}